apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: source
  steps:
    - name: remove
      image: alpine
      script: |
        #!/usr/bin/env sh
        set -eu

        WORKSPACE_SOURCE_PATH="$(workspaces.source.path)"
        echo "Eliminando todos los archivos de ${WORKSPACE_SOURCE_PATH} ..."

        if [ -n "${WORKSPACE_SOURCE_PATH}" ]; then
          # Eliminar archivos y directorios no ocultos ...
          find "${WORKSPACE_SOURCE_PATH}" ! -path "${WORKSPACE_SOURCE_PATH}/?" \
              ! -path "${WORKSPACE_SOURCE_PATH}/.[!.]*" \
              ! -path "${WORKSPACE_SOURCE_PATH}/..?*" \
              | xargs rm -rf

          # ... y eliminar archivos y directorios ocultos (excepto ..)
          find "${WORKSPACE_SOURCE_PATH}" -name ".*" ! -name "." ! -name ".." \
              | xargs rm -rf
        fi
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
spec:
  workspaces:
    - name: source
  params:
    - name: args
      description: Argumentos a pasar a nose
      type: string
      default: " -v"
  steps:
    - name: nosetests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
        nosetests $(params.args)

